using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DataParser.Repository.Migrations
{
    public partial class initiaMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Claim_Staging",
                columns: table => new
                {
                    id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    claim_info_id = table.Column<int>(nullable: true),
                    file_id = table.Column<int>(nullable: true),
                    seq_id = table.Column<int>(nullable: true),
                    action_type = table.Column<string>(type: "char(6)", nullable: true),
                    rre_info_id = table.Column<string>(type: "char(9)", nullable: true),
                    claim_control_num = table.Column<string>(type: "varchar(50)", nullable: true),
                    cms_doi = table.Column<DateTime>(type: "date", nullable: true),
                    industry_doi = table.Column<DateTime>(type: "date", nullable: true),
                    orm_term_date = table.Column<DateTime>(type: "date", nullable: true),
                    venue_state = table.Column<string>(type: "char(2)", nullable: true),
                    lost_time = table.Column<string>(type: "varchar(20)", nullable: true),
                    total_medical_spent = table.Column<decimal>(type: "numeric(11, 2)", nullable: true),
                    office_code = table.Column<string>(type: "char(9)", nullable: true),
                    claim_no = table.Column<string>(type: "varchar(30)", nullable: true),
                    orm_indicator = table.Column<string>(type: "char(1)", nullable: true),
                    tin = table.Column<string>(type: "char(9)", nullable: true),
                    ip_mbi = table.Column<string>(type: "varchar(12)", nullable: true),
                    ip_hicn = table.Column<string>(type: "varchar(12)", nullable: true),
                    ip_ssn = table.Column<string>(type: "char(9)", nullable: true),
                    ip_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    ip_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    ip_middle_initial = table.Column<string>(type: "char(1)", nullable: true),
                    ip_gender = table.Column<string>(type: "char(1)", nullable: true),
                    ip_dob = table.Column<DateTime>(type: "date", nullable: true),
                    ip_dod = table.Column<DateTime>(type: "date", nullable: true),
                    ip_address1 = table.Column<string>(type: "varchar(50)", nullable: true),
                    ip_address2 = table.Column<string>(type: "varchar(50)", nullable: true),
                    ip_city = table.Column<string>(type: "varchar(30)", nullable: true),
                    ip_state = table.Column<string>(type: "char(2)", nullable: true),
                    ip_zip_code = table.Column<string>(type: "char(5)", nullable: true),
                    ip_zip_ext = table.Column<string>(type: "char(4)", nullable: true),
                    ip_phone = table.Column<string>(type: "varchar(10)", nullable: true),
                    ip_phone_ext = table.Column<string>(type: "char(5)", nullable: true),
                    ip_rep_indicator = table.Column<string>(type: "char(1)", nullable: true),
                    ip_rep_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    ip_rep_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    ip_rep_tin = table.Column<string>(type: "char(9)", nullable: true),
                    ip_rep_address1 = table.Column<string>(type: "varchar(50)", nullable: true),
                    ip_rep_address2 = table.Column<string>(type: "varchar(50)", nullable: true),
                    ip_rep_city = table.Column<string>(type: "varchar(30)", nullable: true),
                    ip_rep_state = table.Column<string>(type: "char(2)", nullable: true),
                    ip_rep_zip_code = table.Column<string>(type: "char(5)", nullable: true),
                    ip_rep_zip_ext = table.Column<string>(type: "char(4)", nullable: true),
                    ip_rep_phone = table.Column<string>(type: "varchar(10)", nullable: true),
                    ip_rep_phone_ext = table.Column<string>(type: "char(5)", nullable: true),
                    ip_rep_firm_name = table.Column<string>(type: "varchar(70)", nullable: true),
                    plan_ins_type = table.Column<string>(type: "char(1)", nullable: true),
                    contact_dept = table.Column<string>(type: "varchar(70)", nullable: true),
                    contact_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    contact_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    contact_phone = table.Column<string>(type: "varchar(10)", nullable: true),
                    contact_phone_ext = table.Column<string>(type: "char(5)", nullable: true),
                    no_fault_limit = table.Column<decimal>(type: "numeric(11, 2)", nullable: true),
                    exhaust_date = table.Column<DateTime>(type: "date", nullable: true),
                    adj_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    adj_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    adj_phone = table.Column<string>(type: "varchar(10)", nullable: true),
                    adj_phone_ext = table.Column<string>(type: "char(5) ", nullable: true),
                    adj_email = table.Column<string>(type: "varchar(50)", nullable: true),
                    self_ins_indicator = table.Column<string>(type: "char(1) ", nullable: true),
                    self_ins_type = table.Column<string>(type: "char(1) ", nullable: true),
                    policy_holder_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    policy_holder_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    dba_name = table.Column<string>(type: "varchar(70)", nullable: true),
                    legal_name = table.Column<string>(type: "varchar(70)", nullable: true),
                    policy_no = table.Column<string>(type: "varchar(30)", nullable: true),
                    prd_liability_indicator = table.Column<string>(type: "char(1) ", nullable: true),
                    prd_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    prd_brand_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    prd_manufacturer = table.Column<string>(type: "varchar(40)", nullable: true),
                    prd_alleged_harm = table.Column<string>(type: "varchar(200)", nullable: true),
                    injury_nature = table.Column<string>(type: "varchar(50)", nullable: true),
                    injury_cause = table.Column<string>(type: "char(8)", nullable: true),
                    icd_indicator = table.Column<string>(type: "char(1)", nullable: true),
                    icd_code1 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code2 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code3 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code4 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code5 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code6 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code7 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code8 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code9 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code10 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code11 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code12 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code13 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code14 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code15 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code16 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code17 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code18 = table.Column<string>(type: "varchar(8)", nullable: true),
                    icd_code19 = table.Column<string>(type: "varchar(8)", nullable: true),
                    claimant1_relation = table.Column<string>(type: "char(1)", nullable: true),
                    claimant1_tin = table.Column<string>(type: "char(9)", nullable: true),
                    claimant1_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    claimant1_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant1_middle_initial = table.Column<string>(type: "char(1)", nullable: true),
                    claimant1_org_name = table.Column<string>(type: "varchar(71)", nullable: true),
                    claimant1_address1 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant1_address2 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant1_city = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant1_state = table.Column<string>(type: "char(2)", nullable: true),
                    claimant1_zip_code = table.Column<string>(type: "char(5)", nullable: true),
                    claimant1_zip_ext = table.Column<string>(type: "char(4)", nullable: true),
                    claimant1_phone = table.Column<string>(type: "varchar(10)", nullable: true),
                    claimant1_phone_ext = table.Column<string>(type: "char(5)", nullable: true),
                    claimant1_rep_indicator = table.Column<string>(type: "char(1)", nullable: true),
                    claimant1_rep_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    claimant1_rep_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant1_rep_firm_name = table.Column<string>(type: "varchar(70)", nullable: true),
                    claimant1_rep_tin = table.Column<string>(type: "char(9)", nullable: true),
                    claimant1_rep_address1 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant1_rep_address2 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant1_rep_city = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant1_rep_state = table.Column<string>(type: "char(2)", nullable: true),
                    claimant1_rep_zip_code = table.Column<string>(type: "char(5)", nullable: true),
                    claimant1_rep_zip_ext = table.Column<string>(type: "char(4)", nullable: true),
                    claimant1_rep_phone = table.Column<string>(type: "varchar(10)", nullable: true),
                    claimant1_rep_phone_ext = table.Column<string>(type: "char(5)", nullable: true),
                    claimant1_seq_no = table.Column<int>(nullable: true),
                    claimant2_relation = table.Column<string>(type: "char(1)", nullable: true),
                    claimant2_tin = table.Column<string>(type: "char(9)", nullable: true),
                    claimant2_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    claimant2_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant2_middle_initial = table.Column<string>(type: "char(1)", nullable: true),
                    claimant2_org_name = table.Column<string>(type: "varchar(71)", nullable: true),
                    claimant2_address1 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant2_address2 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant2_city = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant2_state = table.Column<string>(type: "char(2)", nullable: true),
                    claimant2_zip_code = table.Column<string>(type: "char(5)", nullable: true),
                    claimant2_zip_ext = table.Column<string>(type: "char(4)", nullable: true),
                    claimant2_phone = table.Column<string>(type: "varchar(10)", nullable: true),
                    claimant2_phone_ext = table.Column<string>(type: "char(5)", nullable: true),
                    claimant2_rep_indicator = table.Column<string>(type: "char(1)", nullable: true),
                    claimant2_rep_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    claimant2_rep_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant2_rep_firm_name = table.Column<string>(type: "varchar(70)", nullable: true),
                    claimant2_rep_tin = table.Column<string>(type: "char(9)", nullable: true),
                    claimant2_rep_address1 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant2_rep_address2 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant2_rep_city = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant2_rep_state = table.Column<string>(type: "char(2)", nullable: true),
                    claimant2_rep_zip_code = table.Column<string>(type: "char(5)", nullable: true),
                    claimant2_rep_zip_ext = table.Column<string>(type: "char(4)", nullable: true),
                    claimant2_rep_phone = table.Column<string>(type: "varchar(10)", nullable: true),
                    claimant2_rep_phone_ext = table.Column<string>(type: "char(5)", nullable: true),
                    claimant2_seq_no = table.Column<int>(nullable: true),
                    claimant3_relation = table.Column<string>(type: "char(1)", nullable: true),
                    claimant3_tin = table.Column<string>(type: "char(9)", nullable: true),
                    claimant3_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    claimant3_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant3_middle_initial = table.Column<string>(type: "char(1)", nullable: true),
                    claimant3_org_name = table.Column<string>(type: "varchar(71)", nullable: true),
                    claimant3_address1 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant3_address2 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant3_city = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant3_state = table.Column<string>(type: "char(2)", nullable: true),
                    claimant3_zip_code = table.Column<string>(type: "char(5)", nullable: true),
                    claimant3_zip_ext = table.Column<string>(type: "char(4)", nullable: true),
                    claimant3_phone = table.Column<string>(type: "varchar(10)", nullable: true),
                    claimant3_phone_ext = table.Column<string>(type: "char(5)", nullable: true),
                    claimant3_rep_indicator = table.Column<string>(type: "char(1)", nullable: true),
                    claimant3_rep_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    claimant3_rep_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant3_rep_firm_name = table.Column<string>(type: "varchar(70)", nullable: true),
                    claimant3_rep_tin = table.Column<string>(type: "char(9)", nullable: true),
                    claimant3_rep_address1 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant3_rep_address2 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant3_rep_city = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant3_rep_state = table.Column<string>(type: "char(2)", nullable: true),
                    claimant3_rep_zip_code = table.Column<string>(type: "char(5)", nullable: true),
                    claimant3_rep_zip_ext = table.Column<string>(type: "char(4)", nullable: true),
                    claimant3_rep_phone = table.Column<string>(type: "varchar(10)", nullable: true),
                    claimant3_rep_phone_ext = table.Column<string>(type: "char(5)", nullable: true),
                    claimant3_seq_no = table.Column<int>(nullable: true),
                    claimant4_relation = table.Column<string>(type: "char(1)", nullable: true),
                    claimant4_tin = table.Column<string>(type: "char(9)", nullable: true),
                    claimant4_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    claimant4_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant4_middle_initial = table.Column<string>(type: "char(1)", nullable: true),
                    claimant4_org_name = table.Column<string>(type: "varchar(71)", nullable: true),
                    claimant4_address1 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant4_address2 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant4_city = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant4_state = table.Column<string>(type: "char(2)", nullable: true),
                    claimant4_zip_code = table.Column<string>(type: "char(5)", nullable: true),
                    claimant4_zip_ext = table.Column<string>(type: "char(4)", nullable: true),
                    claimant4_phone = table.Column<string>(type: "varchar(10)", nullable: true),
                    claimant4_phone_ext = table.Column<string>(type: "char(5)", nullable: true),
                    claimant4_rep_indicator = table.Column<string>(type: "char(1)", nullable: true),
                    claimant4_rep_last_name = table.Column<string>(type: "varchar(40)", nullable: true),
                    claimant4_rep_first_name = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant4_rep_firm_name = table.Column<string>(type: "varchar(70)", nullable: true),
                    claimant4_rep_tin = table.Column<string>(type: "char(9)", nullable: true),
                    claimant4_rep_address1 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant4_rep_address2 = table.Column<string>(type: "varchar(50)", nullable: true),
                    claimant4_rep_city = table.Column<string>(type: "varchar(30)", nullable: true),
                    claimant4_rep_state = table.Column<string>(type: "char(2)", nullable: true),
                    claimant4_rep_zip_code = table.Column<string>(type: "char(5)", nullable: true),
                    claimant4_rep_zip_ext = table.Column<string>(type: "char(4)", nullable: true),
                    claimant4_rep_phone = table.Column<string>(type: "varchar(10)", nullable: true),
                    claimant4_rep_phone_ext = table.Column<string>(type: "char(5)", nullable: true),
                    claimant4_seq_no = table.Column<int>(nullable: true),
                    tpoc1_date = table.Column<DateTime>(type: "date", nullable: true),
                    tpoc1_amount = table.Column<decimal>(type: "numeric(11, 2)", nullable: true),
                    tpoc1_fund_delayed_date = table.Column<DateTime>(type: "datetime", nullable: true),
                    tpoc1_seq_no = table.Column<int>(nullable: true),
                    tpoc2_date = table.Column<DateTime>(type: "date", nullable: true),
                    tpoc2_amount = table.Column<decimal>(type: "numeric(11, 2)", nullable: true),
                    tpoc2_fund_delayed_date = table.Column<DateTime>(type: "datetime", nullable: true),
                    tpoc2_seq_no = table.Column<int>(nullable: true),
                    tpoc3_date = table.Column<DateTime>(type: "date", nullable: true),
                    tpoc3_amount = table.Column<decimal>(type: "numeric(11, 2)", nullable: true),
                    tpoc3_fund_delayed_date = table.Column<DateTime>(type: "datetime", nullable: true),
                    tpoc3_seq_no = table.Column<int>(nullable: true),
                    tpoc4_date = table.Column<DateTime>(type: "date", nullable: true),
                    tpoc4_amount = table.Column<decimal>(type: "numeric(11, 2)", nullable: true),
                    tpoc4_fund_delayed_date = table.Column<DateTime>(type: "datetime", nullable: true),
                    tpoc4_seq_no = table.Column<int>(nullable: true),
                    tpoc5_date = table.Column<DateTime>(type: "date", nullable: true),
                    tpoc5_amount = table.Column<decimal>(type: "numeric(11, 2)", nullable: true),
                    tpoc5_fund_delayed_date = table.Column<DateTime>(type: "datetime", nullable: true),
                    tpoc5_seq_no = table.Column<int>(nullable: true),
                    future_field1 = table.Column<string>(type: "varchar(50)", nullable: true),
                    future_field2 = table.Column<string>(type: "varchar(50)", nullable: true),
                    future_field3 = table.Column<string>(type: "varchar(50)", nullable: true),
                    future_field4 = table.Column<string>(type: "varchar(50)", nullable: true),
                    future_field5 = table.Column<string>(type: "varchar(50)", nullable: true),
                    future_field6 = table.Column<string>(type: "varchar(50)", nullable: true),
                    future_field7 = table.Column<string>(type: "varchar(50)", nullable: true),
                    future_field8 = table.Column<string>(type: "varchar(50)", nullable: true),
                    future_field9 = table.Column<string>(type: "varchar(50)", nullable: true),
                    future_field10 = table.Column<string>(type: "varchar(50)", nullable: true),
                    created_date = table.Column<DateTime>(type: "datetime", nullable: true),
                    updated_date = table.Column<DateTime>(type: "datetime", nullable: true),
                    status = table.Column<int>(nullable: true),
                    claim_status = table.Column<string>(type: "varchar(50)", nullable: true),
                    account_id = table.Column<int>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Claim_Staging", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "File_Error",
                columns: table => new
                {
                    id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    file_id = table.Column<int>(nullable: true),
                    error_code = table.Column<string>(type: "char(10)", nullable: true),
                    value = table.Column<string>(type: "varchar(200)", nullable: true),
                    seq_id = table.Column<int>(nullable: true),
                    claim_control_number = table.Column<int>(nullable: true),
                    account_id = table.Column<string>(type: "varchar(50)", nullable: true),
                    rre_info_id = table.Column<string>(type: "char(9)", nullable: true),
                    error_date = table.Column<DateTime>(type: "datetime", nullable: true),
                    created_by = table.Column<int>(nullable: true),
                    created_date = table.Column<DateTime>(type: "datetime", nullable: true),
                    updated_by = table.Column<int>(nullable: true),
                    updated_date = table.Column<DateTime>(type: "datetime", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_File_Error", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "File_Info",
                columns: table => new
                {
                    id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    tpra_info_id = table.Column<int>(nullable: true),
                    rreid = table.Column<int>(nullable: true),
                    file_name = table.Column<string>(type: "varchar(100)", nullable: true),
                    file_type = table.Column<string>(type: "varchar(100)", nullable: true),
                    transaction_date = table.Column<DateTime>(type: "date", nullable: true),
                    rec_count = table.Column<int>(nullable: true),
                    claim_count = table.Column<int>(nullable: true),
                    file_status = table.Column<string>(type: "varchar(10)", nullable: true),
                    env = table.Column<string>(type: "char(4)", nullable: true),
                    actual_date = table.Column<DateTime>(type: "datetime", nullable: true),
                    start_date = table.Column<DateTime>(type: "datetime", nullable: true),
                    end_date = table.Column<DateTime>(type: "datetime", nullable: true),
                    received_date = table.Column<DateTime>(type: "datetime", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_File_Info", x => x.id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Claim_Staging");

            migrationBuilder.DropTable(
                name: "File_Error");

            migrationBuilder.DropTable(
                name: "File_Info");
        }
    }
}
